version: '3'

services:
  database_postgres:
    image: postgres:latest
    container_name: database_postgresKH
    environment:
      POSTGRES_PASSWORD: 111111 # Задаємо пароль root користувача
      POSTGRES_DB: comments_user # Створюємо нову базу даних
      POSTGRES_USER: user # Створюємо нового користувача
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
